feat: add AWS Account ID

diff --git a/.github/workflows/aws_cd.yml b/.github/workflows/aws_cd.yml
--- a/.github/workflows/aws_cd.yml
+++ b/.github/workflows/aws_cd.yml
@@ -19,13 +19,26 @@ jobs:
             contents: read
 
         steps:
-            - uses: actions/checkout@v2
+            - uses: actions/checkout@v3
+          
+            - name: Determine AWS Account ID
+              run: |
+                  if [[ "${{ github.ref_name }}" == "dev" ]]; then
+                    echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_DEV }}" >> $GITHUB_ENV
+                  elif [[ "${{ github.ref_name }}" == "homolog" ]]; then
+                    echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_HOML }}" >> $GITHUB_ENV
+                  elif [[ "${{ github.ref_name }}" == "prod" ]]; then
+                    echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_PROD }}" >> $GITHUB_ENV
+                  else
+                    echo "Invalid branch name!" && exit 1
+                  fi
+
             - name: Setup AWS Credentials
               uses: aws-actions/configure-aws-credentials@v2
               with:
-                aws-region: ${{ vars.AWS_REGION }}
-                role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID_DEV }}:role/GithubActionsRole
-                role-session-name: github-action
+                  aws-region: ${{ vars.AWS_REGION }}
+                  role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/GithubActionsRole
+                  role-session-name: github-action
 
             - name: Setting stage and stack name
               run: |
@@ -49,7 +62,7 @@ jobs:
                   cdk deploy --require-approval never
               env:
                   AWS_REGION: ${{ vars.AWS_REGION }}
-                  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID_DEV }}
+                  AWS_ACCOUNT_ID: ${{ env.AWS_ACCOUNT_ID }}
                   STACK_NAME: ${{ env.STACK_NAME }}
                   GITHUB_REF_NAME: ${{ github.ref_name }}
                   MSS_NAME: ${{ github.event.repository.name }}
